'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funkcje automatycznego zapisywania My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property edd_repo_set() As Boolean
            Get
                Return CType(Me("edd_repo_set"),Boolean)
            End Get
            Set
                Me("edd_repo_set") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property edd_repo_dir() As String
            Get
                Return CType(Me("edd_repo_dir"),String)
            End Get
            Set
                Me("edd_repo_dir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property last_language() As String
            Get
                Return CType(Me("last_language"),String)
            End Get
            Set
                Me("last_language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\EDDiscovery\Translations\")>  _
        Public Property lang_mainfile_path() As String
            Get
                Return CType(Me("lang_mainfile_path"),String)
            End Get
            Set
                Me("lang_mainfile_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{0}-{1}.tlf")>  _
        Public Property lang_mainfile_naming() As String
            Get
                Return CType(Me("lang_mainfile_naming"),String)
            End Get
            Set
                Me("lang_mainfile_naming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("example-ex.tlf")>  _
        Public Property lang_exfile_name() As String
            Get
                Return CType(Me("lang_exfile_name"),String)
            End Get
            Set
                Me("lang_exfile_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\EDDiscovery\UserControls\")>  _
        Public Property lang_uc_path() As String
            Get
                Return CType(Me("lang_uc_path"),String)
            End Get
            Set
                Me("lang_uc_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("translation-{0}-uc.tlp")>  _
        Public Property lang_uc_naming() As String
            Get
                Return CType(Me("lang_uc_naming"),String)
            End Get
            Set
                Me("lang_uc_naming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\EliteDangerous\JournalEvents\")>  _
        Public Property lang_je_path() As String
            Get
                Return CType(Me("lang_je_path"),String)
            End Get
            Set
                Me("lang_je_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("translation-{0}-je.tlp")>  _
        Public Property lang_je_naming() As String
            Get
                Return CType(Me("lang_je_naming"),String)
            End Get
            Set
                Me("lang_je_naming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\EliteDangerous\EliteDangerous\")>  _
        Public Property lang_ed_path() As String
            Get
                Return CType(Me("lang_ed_path"),String)
            End Get
            Set
                Me("lang_ed_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("translation-{0}-ed.tlp")>  _
        Public Property lang_ed_naming() As String
            Get
                Return CType(Me("lang_ed_naming"),String)
            End Get
            Set
                Me("lang_ed_naming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property tran_hide_translated() As Boolean
            Get
                Return CType(Me("tran_hide_translated"),Boolean)
            End Get
            Set
                Me("tran_hide_translated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property tran_wordwrap() As Boolean
            Get
                Return CType(Me("tran_wordwrap"),Boolean)
            End Get
            Set
                Me("tran_wordwrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property tran_show_example() As Boolean
            Get
                Return CType(Me("tran_show_example"),Boolean)
            End Get
            Set
                Me("tran_show_example") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property diff_wordwrap() As Boolean
            Get
                Return CType(Me("diff_wordwrap"),Boolean)
            End Get
            Set
                Me("diff_wordwrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property diff_ignore_removed() As Boolean
            Get
                Return CType(Me("diff_ignore_removed"),Boolean)
            End Get
            Set
                Me("diff_ignore_removed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property auto_load_files() As Boolean
            Get
                Return CType(Me("auto_load_files"),Boolean)
            End Get
            Set
                Me("auto_load_files") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property auto_check_edd_repo() As Boolean
            Get
                Return CType(Me("auto_check_edd_repo"),Boolean)
            End Get
            Set
                Me("auto_check_edd_repo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property exmp_wordwrap() As Boolean
            Get
                Return CType(Me("exmp_wordwrap"),Boolean)
            End Get
            Set
                Me("exmp_wordwrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property exmp_show_translation() As Boolean
            Get
                Return CType(Me("exmp_show_translation"),Boolean)
            End Get
            Set
                Me("exmp_show_translation") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.EDDTT.My.MySettings
            Get
                Return Global.EDDTT.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
